"""empty message

Revision ID: 62834483a2ee
Revises: fee2872a9f3c
Create Date: 2021-12-14 21:04:05.111810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62834483a2ee'
down_revision = 'fee2872a9f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
