"""empty message

Revision ID: a84ef21e55e0
Revises: 12a528564f30
Create Date: 2022-01-06 21:07:06.799511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84ef21e55e0'
down_revision = '12a528564f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'apitoken')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('apitoken', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
