"""empty message

Revision ID: e40f6dde46f5
Revises: a84ef21e55e0
Create Date: 2022-01-06 21:08:03.364025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40f6dde46f5'
down_revision = 'a84ef21e55e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('apitoken', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'apitoken')
    # ### end Alembic commands ###
